#version 430 core

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer BufferA {
    float wejscieA[];
};

layout(std430, binding = 1) readonly buffer BufferB {
    float wejscieB[];
};

layout(std430, binding = 2) writeonly buffer BufferResult {
    float wyniki[];
};

void main() {
    uint index = gl_GlobalInvocationID.x;
    wyniki[index] = wejscieA[index] + wejscieB[index];
}
